# Generated by Django 3.2 on 2021-04-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_reg_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_address', models.CharField(max_length=50)),
                ('c_mail_id', models.EmailField(max_length=50)),
                ('c_mob_no', models.CharField(max_length=10)),
                ('c_username', models.CharField(max_length=50)),
                ('c_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='generate_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10)),
                ('b_name', models.CharField(max_length=50)),
                ('mob_num', models.CharField(max_length=10)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('total', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='room_booking_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no_adults', models.CharField(max_length=50)),
                ('name_adults', models.CharField(max_length=500)),
                ('no_child', models.CharField(max_length=50)),
                ('name_child', models.CharField(max_length=500)),
                ('phone_num', models.CharField(max_length=10)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('room_no', models.CharField(max_length=10)),
                ('room_no1', models.CharField(max_length=10)),
            ],
        ),
    ]
