# Generated by Django 3.2 on 2021-04-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=225)),
            ],
        ),
    ]
